In [82]:
import time, requests, os, math, numpy
import pandas as pd
from pandas import DataFrame, Series
from math import pi,sin,cos,asin,sqrt

def download(filename, url):
    # We do not download again if the file already exists
    # TODO: Write the code to download the file from URL
    # and save it in `filename`
    if os.path.exists(filename):
        return (str(filename) + " already exists!")
    else:
        r = requests.get(url)
        r.raise_for_status()
        data = r.text
        f = open(filename, "w", encoding="utf-8")
        f.write(data)
        f.close()
    return (str(filename) + " created!")

In [2]:
download('countries.json', 'https://raw.githubusercontent.com/msyamkumar/cs220-projects/master/spring20/p10/countries.json')

'countries.json already exists!'

In [3]:
countries = pd.read_json('countries.json')

In [4]:
countries.head()

,area,birth-rate,coastline,continent,country,death-rate,gdp-per-capita,infant-mortality,literacy,net-migration,phones,population,region
0,756950,15.23,0.85,South America,Chile,5.81,9900,8.80,"96,2",0.00,"213,0",16134219,LATIN AMER. & CARIB
1,665,17.80,24.21,Asia,Bahrain,4.14,16900,17.27,"89,1",1.05,"281,3",698585,NEAR EAST
2,22966,28.84,1.68,North America,Belize,5.72,4900,25.69,"94,1",0.00,"115,7",287730,LATIN AMER. & CARIB
3,582650,39.72,0.09,Africa,Kenya,14.02,1000,61.47,"85,1",-0.10,"8,1",34707817,SUB-SAHARAN AFRICA
4,11854,33.05,3.12,Australia,Marshall Islands,4.78,1600,29.45,"93,7",-6.04,"91,2",60422,OCEANIA

In [5]:
#q1
len(countries)

174

In [6]:
#Q2: what is the total population across all the countries in our dataset?
# find_sum = lambda x:x.sum()
# total_data = countries.apply(find_sum)
# total_data['population']
countries['population'].sum()

6261901793

In [7]:
download('capitals.json','https://raw.githubusercontent.com/msyamkumar/cs220-projects/master/spring20/p10/capitals.json')

'capitals.json already exists!'

In [8]:
capitals = pd.read_json('capitals.json')
capitals.head()

       country       capital   latitude  longitude
0  Afghanistan         Kabul  34.516667  69.183333
1      Albania        Tirana  41.316667  19.816667
2      Algeria       Algiers  36.750000   3.050000
3     Anguilla    The Valley  18.216667 -63.050000
4    Argentina  Buenos Aires -34.583333 -58.666667

In [9]:
#Q3: What are the capital names in capitals.json?
capital_names = list(capitals['capital'])
sorted(capital_names, 
       #key = lambda x:x[0], 
       reverse = True)

['Zagreb',
 'Yerevan',
 'Yaounde',
 'Windhoek',
 'Wellington',
 'Washington, D.C.',
 'Warsaw',
 'Vilnius',
 'Vientiane',
 'Vienna',
 'Victoria',
 'Valletta',
 'Vaduz',
 'Ulaanbaatar',
 'Tunis',
 'Tripoli',
 'Tokyo',
 'Tirana',
 'Thimphu',
 'The Valley',
 'Tehran',
 'Tegucigalpa',
 'Tbilisi',
 'Tashkent',
 'Tallinn',
 'Taipei',
 'Suva',
 'Stockholm',
 'Sofia',
 'Singapore',
 'Santo Domingo',
 'Santiago',
 'Sanaa',
 'San Salvador',
 'San Marino',
 'San Juan',
 'San Jose',
 'Saint George’s',
 'Roseau',
 'Rome',
 'Riyadh',
 'Riga',
 'Reykjavik',
 'Rabat',
 'Quito',
 'Pretoria',
 'Praia',
 'Prague',
 'Porto-Novo',
 'Port-au-Prince',
 'Port-Vila',
 'Port Moresby',
 'Port Louis',
 'Phnom Penh',
 'Paris',
 'Paramaribo',
 'Papeete',
 'Panama City',
 'Ouagadougou',
 'Ottawa',
 'Oslo',
 'Oranjestad',
 'N’Djamena',
 'Nuku’alofa',
 'Noumea',
 'Nouakchott',
 'Niamey',
 'New Delhi',
 'Nairobi',
 'Muscat',
 'Moscow',
 'Moroni',
 'Montevideo',
 'Monrovia',
 'Monaco',
 'Mogadishu',
 'Minsk',
 'Mexico City',
 'Melekeok',
 'Mbabane',
 'Maseru',
 'Maputo',
 'Manila',
 'Manama',
 'Managua',
 'Male',
 'Malabo',
 'Majuro',
 'Madrid',
 'Luxembourg',
 'Lusaka',
 'London',
 'Lome',
 'Ljubljana',
 'Lisbon',
 'Lima',
 'Lilongwe',
 'Libreville',
 'La Paz',
 'Kyiv',
 'Kuwait City',
 'Kuala Lumpur',
 'Kingstown',
 'Kingston',
 'Kigali',
 'Khartoum',
 'Kathmandu',
 'Kampala',
 'Kabul',
 'Jerusalem',
 'Jamestown',
 'Jakarta',
 'Islamabad',
 'Helsinki',
 'Havana',
 'Harare',
 'Hanoi',
 'Hamilton',
 'Hagatna',
 'Guatemala City',
 'Georgetown',
 'George Town',
 'Gaborone',
 'Freetown',
 'Dushanbe',
 'Dublin',
 'Doha',
 'Djibouti',
 'Dhaka',
 'Dar es Salaam',
 'Damascus',
 'Dakar',
 'Copenhagen',
 'Conakry',
 'Colombo',
 'Chisinau',
 'Castries',
 'Caracas',
 'Canberra',
 'Cairo',
 'Bujumbura',
 'Buenos Aires',
 'Budapest',
 'Bucharest',
 'Brussels',
 'Bridgetown',
 'Brasilia',
 'Bogota',
 'Bissau',
 'Bishkek',
 'Bern',
 'Berlin',
 'Belmopan',
 'Beirut',
 'Beijing',
 'Bangkok',
 'Bamako',
 'Baku',
 'Baghdad',
 'Athens',
 'Asuncion',
 'Astana',
 'Asmara',
 'Ashgabat',
 'Apia',
 'Antananarivo',
 'Ankara',
 'Amsterdam',
 'Amman',
 'Algiers',
 'Addis Ababa',
 'Accra',
 'Abuja',
 'Abu Dhabi']

In [10]:
def find_corresponding_values(name, name_column, column):
    values = list(capitals[column])
    idx = None
    for i in range(len(values)):
        if values[i] == name:
            idx = i
    new_column = list(capitals[name_column])
    return new_column[idx]

In [11]:
#Q4: What is the capital of Italy?
find_corresponding_values(name = 'Italy', column = 'country', name_column = 'capital')

'Rome'

In [12]:
#Q5: Which country's capital is Brussels?
find_corresponding_values('Brussels','country','capital')

'Belgium'

In [13]:
#Q6: Which 7 countries have the southern-most capitals?
def return_sorted_df(key, nums, key_2): 
    return capitals.sort_values(by=[key])[key_2].values.tolist()[:nums]
return_sorted_df('latitude',7,'country')

['New Zealand',
 'Australia',
 'Uruguay',
 'Argentina',
 'Chile',
 'Lesotho',
 'Swaziland']

In [14]:
#Q7: Which 10 countries have the capitals closest to the North Pole?
funcs = lambda x,y,z : capitals.sort_values(by=[x], ascending = False)[y].values.tolist()[:z]
funcs('latitude','country',10)

['Iceland',
 'Finland',
 'Norway',
 'Estonia',
 'Sweden',
 'Latvia',
 'Russia',
 'Denmark',
 'Lithuania',
 'Belarus']

In [317]:
#Q8: What is the distance between Camp Randall Stadium and the Wisconsin State Capital?
#Haversine Formula (from R.W. Sinnott, "Virtues of the Haversine", Sky and Telescope, vol. 68, no. 2, 1984, p. 159):
def calculate_distance(lat1,lon1,lat2,lon2):
    pi = math.pi
    R = 3956
    lat1 = math.radians(lat1)
    lat2 = math.radians(lat2)
    lon1 = math.radians(lon1)
    lon2 = math.radians(lon2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = (sin(dlat/2.0)) ** 2.0 + cos(lat1) * cos(lat2) * (sin(dlon/2.0)) ** 2.0
    a = sqrt(a ** 2.0)
    c = 2.0 * asin(min(1,sqrt(a)))
    d = R * c
    return d

In [319]:
calculate_distance(43.070231,-89.411893,43.074645,-89.384113)

1.433899492072933

In [320]:
def find_distance(country1,country2):
    lat1 = float(capitals[(capitals['country'] == country1)]['latitude'])
    lon1 = float(capitals[(capitals['country'] == country1)]['longitude'])
    lat2 = float(capitals[(capitals['country'] == country2)]['latitude'])
    lon2 = float(capitals[(capitals['country'] == country2)]['longitude'])
    return calculate_distance(lat1,lon1,lat2,lon2)

In [321]:
#Q9: What is the distance between Germany and Norway?
find_distance('Germany','Norway')

520.8581822565818

In [346]:
#Q10: What are the distances between Switzerland, Netherlands and Spain?
def find_group_distance(list_1, *args):
    df = DataFrame()
    list_2 = list_1
    for i in args:
        list_2 = i
    for i in list_2:
        Distance_list = []
        for j in list_1:
            if i == j:
                Distance_list.append(None)
            else:
                Distance_list.append(find_distance(i,j))
        df[i] = Distance_list
        df.set_index([list_1], inplace = True)
    return df

In [347]:
#Q10: What are the distances between Switzerland, Netherlands and Spain?
find_group_distance(['Switzerland','Netherlands','Spain'])

             Switzerland  Netherlands       Spain
Switzerland          NaN   392.028643  714.804467
Netherlands   392.028643          NaN  919.684100
Spain         714.804467   919.684100         NaN

In [348]:
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d

,Chile,Guyana,Colombia,Suriname,Brazil,Bolivia,Venezuela,Argentina,Peru,Ecuador,Uruguay,Paraguay
Chile,NaN,2897.553095,2636.644599,2895.810776,1869.737031,1180.741903,3043.657689,690.784168,1531.480189,2350.207788,833.403262,963.635535
Guyana,2897.553095,NaN,1105.066312,215.336336,1709.071018,1747.772670,646.969843,2857.520462,1837.860149,1483.193753,2878.638295,2214.288286
Colombia,2636.644599,1105.066312,NaN,1303.405134,2275.516286,1512.119255,639.361118,2885.355610,1167.505359,451.004119,2962.230943,2337.615967
Suriname,2895.810776,215.336336,1303.405134,NaN,1572.674232,1778.772975,861.456786,2799.886429,1944.750017,1661.699022,2809.744412,2153.855447
Brazil,1869.737031,1709.071018,2275.516286,1572.674232,NaN,1342.297074,2228.690679,1459.139733,1967.770515,2344.584922,1412.096335,908.185710
Bolivia,1180.741903,1747.772670,1512.119255,1778.772975,1342.297074,NaN,1865.131181,1379.455701,669.926372,1326.758656,1467.253638,906.799256
Venezuela,3043.657689,646.969843,639.361118,861.456786,2228.690679,1865.131181,NaN,3157.624051,1705.418003,1088.064117,3207.352176,2544.799572
Argentina,690.784168,2857.520462,2885.355610,2799.886429,1459.139733,1379.455701,3157.624051,NaN,1936.465790,2696.149591,143.069943,646.036441
Peru,1531.480189,1837.860149,1167.505359,1944.750017,1967.770515,669.926372,1705.418003,1936.465790,NaN,823.054491,2046.571589,1558.635236
Ecuador,2350.207788,1483.193753,451.004119,1661.699022,2344.584922,1326.758656,1088.064117,2696.149591,823.054491,NaN,2791.196721,2218.650964
Uruguay,833.403262,2878.638295,2962.230943,2809.744412,1412.096335,1467.253638,3207.352176,143.069943,2046.571589,2791.196721,NaN,667.699386
Paraguay,963.635535,2214.288286,2337.615967,2153.855447,908.185710,906.799256,2544.799572,646.036441,1558.635236,2218.650964,667.699386,NaN

1899.4232758714027

In [429]:
this_nan = list(filter(no_nan,sa_countries_d['Chile'].tolist()))[0]
for i in list(filter(no_nan,sa_countries_d['Chile'].tolist())):
    print(i != this_nan)

True
True
True
True
True
True
True
True
True
True
True
True

In [427]:
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
def no_nan(a):
    return a != this_nan
def new_sum(x):
    return sum(list(filter(no_nan, x.tolist())))/len(select_countries('continent','South America'))
def find_avg(x):
    return sa_countries_d[x].describe()['mean']

In [430]:
#Q12: What is the most central country in the South American continent?
sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x:find_avg(x))
# new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
sa_countries_d['Avg'].sort_values(ascending = True).index[0]

KeyError: "None of [Index([             'NaN', 2897.5530949080326, 2636.6445991563364,\n        2895.810775872252, 1869.7370307769718, 1180.7419027173523,\n        3043.657689195007,  690.7841681904447, 1531.4801894259174,\n       2350.2077877266884,  833.4032616952479,  963.6355349211822],\n      dtype='object')] are in the [columns]"

In [340]:
#Q13: What is the least central country in South America?
sa_to_all_distance = find_group_distance(list(countries['country']),select_countries('continent','South America'))
new_sa_to_all_distance = sa_to_all_distance.copy(deep=True)
new_sa_to_all_distance['Sum'] = new_sa_to_all_distance.apply(lambda x: new_sum(x))
new_sa_to_all_distance['Sum'].sort_values(ascending = True).index[0]

'Suriname'

In [345]:
sa_to_all_distance.describe()

,Chile,Guyana,Colombia,Suriname,Brazil,Bolivia,Venezuela,Argentina,Peru,Ecuador,Uruguay,Paraguay
count,174.00000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.0000,174.000000
unique,174.00000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.0000,174.000000
top,6200.47791,7678.697133,7935.975818,5887.813125,3321.563307,7422.722216,6256.319034,7679.814874,2046.571589,6654.626344,4095.1544,7421.917722
freq,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000

In [180]:
all_distance = find_group_distance(list(countries['country']))

,Chile,Bahrain,Belize,Kenya,Marshall Islands,Liberia,Spain,Sri Lanka,Oman,Malta,...,Yemen,Canada,Cayman Islands,Malawi,Azerbaijan,Algeria,Iceland,Tonga,Haiti,Chad
Chile,NaN,2463.91,3503.84,594.421,2605.3,520.662,6087.44,3841.49,3749.02,5199.44,...,5960.21,5444.42,3607.15,1086.58,7528.64,4022.74,6587.48,3612.05,3588.3,1483.76
Bahrain,2463.91,NaN,577.715,1931.18,4252.73,3123.45,2118.18,1810.46,200.559,465.392,...,694.472,2221.7,4958.21,2795.63,976.499,1806.43,3092.63,2413.35,4898.37,1834.7
Belize,3503.84,577.715,NaN,1107.96,481.623,377.552,1822.9,966.172,320.029,1388.8,...,1202.44,1943.93,115.39,2097.38,2003.86,1123.82,3214.54,2760.63,164.612,934.554
Kenya,594.421,1931.18,1107.96,NaN,3367.58,1794.54,2490.65,1506.71,1729.59,2532.26,...,1117.62,3505.14,3861.21,876.937,2837.57,2800.04,4665.07,3052.84,3752.16,1194.49
Marshall Islands,2605.3,4252.73,481.623,3367.58,NaN,7707.05,6498.32,4440.98,1721.64,2513.7,...,6286.47,3387.5,5503.83,2969.6,5300.92,5897.52,5392.1,1844.59,6050.02,6911.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Algeria,4022.74,1806.43,1123.82,2800.04,5897.52,2231.05,224.151,4118.02,1122.45,290.6,...,1443.06,1543.71,4231.1,3572.17,2290.16,NaN,2005.93,3109.65,3976.02,1806.49
Iceland,6587.48,3092.63,3214.54,4665.07,5392.1,4016.27,1524.05,5014.48,2867.47,1850.17,...,2557.88,1454.92,3676.49,5468.36,1483.41,2005.93,NaN,4621.71,3601.85,3814.48
Tonga,3612.05,2413.35,2760.63,3052.84,1844.59,6895.71,9281.92,4349.21,2755.32,5298.5,...,7345.01,4135.45,3614.73,2547.37,8398.05,3109.65,4621.71,NaN,4277.83,6196.78
Haiti,3588.3,4898.37,164.612,3752.16,6050.02,4233.66,4026.17,8122.33,1690.88,2356.85,...,7362.69,1858.12,580.333,3480.19,7153.69,3976.02,3601.85,4277.83,NaN,5482.85
Chad,1483.76,1834.7,934.554,1194.49,6911.3,1732.45,1560.53,3754.08,1028.08,1642.03,...,1824.38,3076.11,5825.22,1870.89,872.307,1806.49,3814.48,6196.78,5482.85,NaN

In [258]:
sa_to_all_distance.max(axis = 1)

Chile         8391.626342
Guyana        9755.935302
Colombia      4366.823630
Suriname     10205.337717
Brazil       11384.036445
Bolivia       8704.489724
Venezuela     6330.084855
Argentina    12428.140538
Peru         10536.608256
Ecuador      11644.361185
Uruguay      12428.140538
Paraguay     12428.140538
dtype: float64

In [250]:
#Q14: How close is each country in South America to it's nearest neighbor?

'Colombia'

In [298]:
sa_to_all_distance

,Chile,Bahrain,Belize,Kenya,Marshall Islands,Liberia,Spain,Sri Lanka,Oman,Malta,...,Yemen,Canada,Cayman Islands,Malawi,Azerbaijan,Algeria,Iceland,Tonga,Haiti,Chad
Chile,NaN,2463.910069,3503.842610,594.420536,2605.302403,520.662142,6087.437079,3841.485771,3749.018493,5199.438329,...,5960.205131,5444.421789,3607.145430,1086.582721,7528.641211,4022.744635,6587.484308,3612.047909,3588.298638,1483.756551
Guyana,2722.05,4487.426128,641.066880,3021.480565,6140.516377,3036.299394,2285.197791,7096.857748,1887.722690,829.362726,...,6124.409141,2700.992168,1664.074172,2658.673729,5635.944458,3648.306055,4153.879038,5053.290186,1205.662229,4394.797407
Colombia,2627.74,538.930441,875.322677,1092.244074,1852.918306,1392.136687,2896.885810,2346.107171,1181.719218,2354.296014,...,2357.448797,2818.159196,1002.127066,924.424360,3391.836839,1807.438961,4061.775764,2456.502188,961.213021,1691.961942
Suriname,2619.54,4505.212499,696.523336,2987.501019,6374.834445,2899.283892,2045.549545,7169.504262,1931.738759,504.007792,...,6083.251850,2780.996991,1880.680594,2605.187173,5582.998951,3620.233047,4195.302087,5316.660035,1407.113057,4313.565078
Brazil,1611.52,2926.550997,2330.990632,2705.675500,6738.300197,2028.637497,5005.148705,7084.474666,2248.594693,4186.559226,...,6659.992479,4154.634015,1016.811586,2151.392711,8100.801376,2387.753925,5417.671758,6418.633773,1684.594752,3515.419264
Bolivia,1174.42,2582.766952,2339.471087,2646.286595,4761.364066,2830.714386,5479.385597,6070.650133,2368.040944,4315.048726,...,6446.050848,4271.335773,2355.891175,2140.498918,7755.593139,1994.527142,5350.687630,4574.915816,2406.600344,3819.075256
Venezuela,3036.13,3072.947210,500.195437,2200.988537,4189.738004,2635.534812,3551.146244,5104.834047,713.035506,2530.461872,...,4704.830454,2406.512281,266.640473,526.862814,5298.718971,1634.801143,3526.798877,4455.029659,492.361113,3546.824944
Argentina,558.746,1688.578048,3598.311277,2167.010222,5700.581335,1643.170719,6714.793660,6842.127989,3635.308204,5569.919932,...,8290.544960,5499.647931,3366.487408,1897.352116,10861.730785,3536.135929,6619.314324,6108.819615,3532.657067,3300.625783
Peru,1451.22,5616.520360,2018.809199,3486.754148,5696.137441,4456.344765,2346.670153,7841.120427,2971.820806,1902.123566,...,6709.256760,3967.952983,2181.525352,2549.572819,5652.685952,5258.136131,5636.312641,4744.075149,2133.295395,5788.003415
Ecuador,2265.04,5522.247550,1200.049421,3645.927131,5844.110374,4639.522517,3722.703477,8407.041419,2395.547354,1345.154229,...,7722.794033,3151.641198,1360.651364,2901.941339,6927.578334,4951.434206,4912.746402,4788.653069,1359.149631,6012.620650
Uruguay,661.036,1154.339119,3618.958075,1948.375500,5584.845888,1090.456569,6546.872491,6502.133538,3681.753498,5519.745027,...,7920.540917,5511.926874,3321.178443,1753.483557,10170.384435,3727.841167,6670.044204,6051.015249,3505.371267,2931.853636
Paraguay,191.276,6083.445971,2911.515179,3615.107546,7330.216616,3963.966159,2666.395905,8476.878991,3769.216832,3418.648437,...,5730.961733,4908.068663,3481.620111,2491.097784,4452.884337,5520.819152,6358.156000,5997.526698,3195.775971,5527.030514

In [305]:
sa_to_all_distance.describe().loc['max'].sort_values()

Malawi          2901.941339
Seychelles      2966.745334
Aruba           3173.628809
El Salvador     3202.202209
Grenada         3216.762938
                   ...
India          12428.140538
Malaysia       12428.140538
Uzbekistan     12428.140538
Nepal          12428.140538
Taiwan         12428.140538
Name: max, Length: 162, dtype: float64

In [295]:
sa_to_all_distance.loc['Guyana']

TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'str'

In [342]:
no_nan

In [291]:
def drop_nan(x):
    return x.drop([x])

drop_nan(sa_to_all_distance.loc['Guyana'])

Bahrain             4487.43
Belize              641.067
Kenya               3021.48
Marshall Islands    6140.52
Liberia              3036.3
                     ...
Algeria             3648.31
Iceland             4153.88
Tonga               5053.29
Haiti               1205.66
Chad                 4394.8
Name: Guyana, Length: 173, dtype: object

In [ ]:
def sort_omit_nan(x):
    return sa_to_all_distance.loc[x].astype(float).sort_values(asceding = True)

In [285]:
newhaha = sa_to_all_distance.loc['Chile'].astype(float).sort_values(ascending = True)
newhaha

Paraguay      191.276223
Ghana         244.857368
Liberia       520.662142
Argentina     558.746060
Kenya         594.420536
                ...
Sweden       8095.663527
Mongolia     8180.770783
Finland      8280.652270
Estonia      8391.626342
Chile                NaN
Name: Chile, Length: 174, dtype: float64

In [ ]:
newhaha.drop([x])

In [275]:
sa_countries_d.apply(lambda x:sort_drop_nan(x))

TypeError: '<' not supported between instances of 'float' and 'str'

In [202]:
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
def find_furthest(x):
    return list(filter(no_nan, x.tolist()))
list_1 = new_sa_countries_d.apply(lambda x: find_furthest(x), axis=1)
list_1

Chile        [2722.0467381882345, 2627.7425515595132, 2619....
Guyana       [2722.0467381882345, 306.961195846998, 194.095...
Colombia     [2627.7425515595132, 306.961195846998, 404.499...
Suriname     [2619.541708301451, 194.0954579326229, 404.499...
Brazil       [1611.516694258847, 1410.44248560734, 1532.265...
Bolivia      [1174.4177277525266, 1513.2836218921361, 1461....
Venezuela    [3036.1315710902977, 299.06173957486305, 422.6...
Argentina    [558.7460599242573, 2857.110112021213, 2730.58...
Peru         [1451.2220662159257, 1732.6891284596957, 1147....
Ecuador      [2265.0375738854623, 1382.9388031393446, 316.8...
Uruguay      [661.0358666813381, 2872.7637598287142, 2756.0...
Paraguay     [191.27622328530228, 2214.278648123251, 2025.8...
dtype: object

In [ ]:
#Q12: What is the most central country in the South American continent?
new_sa_countries_d['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x), axis=1)
# new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d['Avg'].sort_values(ascending = False).index[0]

In [ ]:
#Q15: How far is each country in South America to it's furthest neighbor?
my_df = pd.DataFrame(data=[4,5,6,7], index='sacountry', columns=['A'])
print(pd.DataFrame(my_df))
far_dis_table = DataFrame()
far_dis_table.set_index([list(select_countries('continent','South America'))], inplace = True)

In [343]:
history

import time, requests, os, math
import pandas as pd
from pandas import DataFrame, Series
from math import pi,sin,cos,asin,sqrt

def download(filename, url):
    # We do not download again if the file already exists
    # TODO: Write the code to download the file from URL
    # and save it in `filename`
    if os.path.exists(filename):
        return (str(filename) + " already exists!")
    else:
        r = requests.get(url)
        r.raise_for_status()
        data = r.text
        f = open(filename, "w", encoding="utf-8")
        f.write(data)
        f.close()
    return (str(filename) + " created!")
download('countries.json', 'https://raw.githubusercontent.com/msyamkumar/cs220-projects/master/spring20/p10/countries.json')
countries = pd.read_json('countries.json')
countries.head()
#q1
len(countries)
#Q2: what is the total population across all the countries in our dataset?
# find_sum = lambda x:x.sum()
# total_data = countries.apply(find_sum)
# total_data['population']
countries['population'].sum()
download('capitals.json','https://raw.githubusercontent.com/msyamkumar/cs220-projects/master/spring20/p10/capitals.json')
capitals = pd.read_json('capitals.json')
capitals.head()
#Q3: What are the capital names in capitals.json?
capital_names = list(capitals['capital'])
sorted(capital_names,
       #key = lambda x:x[0],
       reverse = True)
def find_corresponding_values(name, name_column, column):
    values = list(capitals[column])
    idx = None
    for i in range(len(values)):
        if values[i] == name:
            idx = i
    new_column = list(capitals[name_column])
    return new_column[idx]
#Q4: What is the capital of Italy?
find_corresponding_values(name = 'Italy', column = 'country', name_column = 'capital')
#Q5: Which country's capital is Brussels?
find_corresponding_values('Brussels','country','capital')
#Q6: Which 7 countries have the southern-most capitals?
def return_sorted_df(key, nums, key_2):
    return capitals.sort_values(by=[key])[key_2].values.tolist()[:nums]
return_sorted_df('latitude',7,'country')
#Q7: Which 10 countries have the capitals closest to the North Pole?
funcs = lambda x,y,z : capitals.sort_values(by=[x], ascending = False)[y].values.tolist()[:z]
funcs('latitude','country',10)
#Q8: What is the distance between Camp Randall Stadium and the Wisconsin State Capital?
#Haversine Formula (from R.W. Sinnott, "Virtues of the Haversine", Sky and Telescope, vol. 68, no. 2, 1984, p. 159):
def calculate_distance(lat1,lon1,lat2,lon2):
    pi = math.pi
    R = 3956
    dlon = math.radians(lon2) - math.radians(lon1)
    dlat = math.radians(lat2) - math.radians(lat1)
    a = (sin(dlat/2)) ** 2 + cos(lat1) * cos(lat2) * (sin(dlon/2)) ** 2
    a = sqrt(a ** 2)
    c = 2 * asin(min(1,sqrt(a)))
    d = R * c
    return d
calculate_distance(43.070231,-89.411893,43.074645,-89.384113)
def find_distance(country1,country2):
    lat1 = float(capitals[(capitals['country'] == country1)]['latitude'])
    lon1 = float(capitals[(capitals['country'] == country1)]['longitude'])
    lat2 = float(capitals[(capitals['country'] == country2)]['latitude'])
    lon2 = float(capitals[(capitals['country'] == country2)]['longitude'])
    return calculate_distance(lat1,lon1,lat2,lon2)
#Q9: What is the distance between Germany and Norway?
find_distance('Germany','Norway')
#Q10: What are the distances between Switzerland, Netherlands and Spain?
def find_group_distance(list_1):
    df = DataFrame()
    for i in list_1:
        Distance_list = []
        for j in list_1:
            if i == j:
                Distance_list.append('NaN')
            else:
                Distance_list.append(find_distance(i,j))
        df[i] = Distance_list
        df.set_index([list_1], inplace = True)
    return df
find_group_distance(['Switzerland','Netherlands','Spain'])
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])


find_group_distance(select_countries('continent','South America'))
for i in Newlist:
    print(i)
lat1,lon1,lat2,lon2 = map(43.070231,-89.411893,43.074645,-89.384113)
(lat1,lon1,lat2,lon2) = [43.070231,-89.411893,43.074645,-89.384113]
(lat1,lon1,lat2,lon2) = [43.070231,-89.411893,43.074645,-89.384113]
dlon = math.radians(lon2) - math.radians(lon1)
dlat = math.radians(lat2) - math.radians(lat1)
(lat1,lon1,lat2,lon2) = [43.070231,-89.411893,43.074645,-89.384113]
dlon = math.radians(lon2) - math.radians(lon1)
dlat = math.radians(lat2) - math.radians(lat1)
dlon
dlat
(lat1,lon1,lat2,lon2) = [43.070231,-89.411893,43.074645,-89.384113]
dlon = math.radians(lon2) - math.radians(lon1)
dlat = math.radians(lat2) - math.radians(lat1)
dlon
dlat
(lat1,lon1,lat2,lon2) = [43.070231,-89.411893,43.074645,-89.384113]
dlon1 = math.radians(lon2) - math.radians(lon1)
dlat1 = math.radians(lat2) - math.radians(lat1)
dlon1
dlat1
dlon = math.radians(lon2 - lon1)
dlat = math.radians(lat2 - lat1)
dlon
dlat
calculate_distance(43.070231,-89.411893,43.074645,-89.384113)/3956
a = (sin(dlat/2)) ** 2 + cos(lat1) * cos(lat2) * (sin(dlon/2)) ** 2
a
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d
DataFrame.mean(sa_countries_d, axis=None, skipna=None, level=None, numeric_only=None, **kwargs)[source]¶
DataFrame.mean(sa_countries_d, axis=None, skipna=None, level=None, numeric_only=None, **kwargs)
DataFrame.mean(sa_countries_d, axis=None, skipna=None, level=None, numeric_only=None)
DataFrame.mean(sa_countries_d, axis=0, skipna=None, level=None, numeric_only=None)
DataFrame.mean(sa_countries_d, axis=0, skipna=None)
sa_countries_d.mean()
import pandas as pd

mydictionary = {'names': ['Somu', 'Kiku', 'Amol', 'Lini'],
    'physics': [68, 74, 77, 78],
    'chemistry': [84, 56, 73, 69],
    'algebra': [78, 88, 82, 87]}

# create dataframe
df_marks = pd.DataFrame(mydictionary)
print('DataFrame\n----------')
print(df_marks)

# calculate mean
mean = df_marks.mean()
print('\nMean\n------')
print(mean)
import pandas as pd

mydictionary = {'names': ['Somu', 'Kiku', 'Amol', 'Lini'],
    'physics': [68, 74, 77, 78],
    'chemistry': [84, 56, 73, 69],
    'algebra': [78, 88, 82, 87]}

# create dataframe
df_marks = pd.DataFrame(mydictionary)
print('DataFrame\n----------')
print(df_marks)

# calculate mean
mean = df_marks.mean()
sa_countries_d.mean()
print(sa_countries_d.mean())
sa_countries_d.mean(0)
sa_countries_d.mean()
sa_countries_d.mean(axis = 1)
sa_countries_d.mean(axis = 1,numeric_only=True)
sa_countries_d.mean(axis = 1,skipna = True)
sa_countries_d.mean(axis = 1)
#Q12: What is the most central country in the South American continent?
**kwargs
def a(x):
    return if x != "NaN"
#Q12: What is the most central country in the South American continent?

def a(x):
    return if x != "NaN"
#Q12: What is the most central country in the South American continent?

def a(x):
    return x: x != "NaN"
#Q12: What is the most central country in the South American continent?

def a(x):
    if x != "NaN"
    return x
#Q12: What is the most central country in the South American continent?

def a(x):
    if x != "NaN":
    return x
#Q12: What is the most central country in the South American continent?

def a(x):
    if x != "NaN":
        return x
sa_countries_d.mean(axis = 1, **kwargs = a)
#Q12: What is the most central country in the South American continent?
sa_countries_d.values
#Q12: What is the most central country in the South American continent?
type(sa_countries_d.values)
#Q12: What is the most central country in the South American continent?
sa_countries_d.values
#Q12: What is the most central country in the South American continent?
sa_countries_d.values[1]
#Q12: What is the most central country in the South American continent?
sa_countries_d.values[1].values
#Q12: What is the most central country in the South American continent?
sa_countries_d.values[1]
#Q12: What is the most central country in the South American continent?
sa_countries_d.values[1]
list(filter(lambda x:x != 'NaN',sa_countries_d))
#Q12: What is the most central country in the South American continent?
sa_countries_d.values[1]
list(filter(lambda x:x != 'NaN',sa_countries_d.values))
#Q12: What is the most central country in the South American continent?
sa_countries_d.values[1]
list(filter(lambda x:x != 'NaN',sa_countries_d.values[1]))
sa_countries_d.values.mean(axis = 1, )
sa_countries_d.values.mean(axis = 1)
sa_countries_d.values(axis = 1)
sa_countries_d.mean(axis = 1)
calculate_distance(43.070231,-89.411893,43.074645,-89.384113)
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = df.apply(lambda x: x.sum(), axis=1)
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: x.sum(), axis=1)
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: x.sum(), axis=0)
sa_countries_d.apply(lambda x: x.sum(), axis=1)
#Q10: What are the distances between Switzerland, Netherlands and Spain?
def find_group_distance(list_1):
    df = DataFrame()
    for i in list_1:
        Distance_list = []
        for j in list_1:
            if i == j:
                Distance_list.append(NaN)
            else:
                Distance_list.append(find_distance(i,j))
        df[i] = Distance_list
        df.set_index([list_1], inplace = True)
    return df
#Q10: What are the distances between Switzerland, Netherlands and Spain?
find_group_distance(['Switzerland','Netherlands','Spain'])
#Q10: What are the distances between Switzerland, Netherlands and Spain?
def find_group_distance(list_1):
    df = DataFrame()
    for i in list_1:
        Distance_list = []
        for j in list_1:
            if i == j:
                Distance_list.append('NaN')
            else:
                Distance_list.append(find_distance(i,j))
        df[i] = Distance_list
        df.set_index([list_1], inplace = True)
    return df
#Q10: What are the distances between Switzerland, Netherlands and Spain?
find_group_distance(['Switzerland','Netherlands','Spain'])
sa_countries_d.apply(lambda x: x.sum(), axis=1)
filter(numpy.isnan(x),sa_countries_d.values[1])
# sa_countries_d.apply(lambda x: x.sum(), axis=1)
filter(numpy.isnan(x),sa_countries_d.values[1])
import time, requests, os, math, numpy
import pandas as pd
from pandas import DataFrame, Series
from math import pi,sin,cos,asin,sqrt

def download(filename, url):
    # We do not download again if the file already exists
    # TODO: Write the code to download the file from URL
    # and save it in `filename`
    if os.path.exists(filename):
        return (str(filename) + " already exists!")
    else:
        r = requests.get(url)
        r.raise_for_status()
        data = r.text
        f = open(filename, "w", encoding="utf-8")
        f.write(data)
        f.close()
    return (str(filename) + " created!")
# sa_countries_d.apply(lambda x: x.sum(), axis=1)
filter(numpy.isnan(x),sa_countries_d.values[1])
# sa_countries_d.apply(lambda x: x.sum(), axis=1)
filter(numpy.isnan(),sa_countries_d.values[1])
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d.values
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d.values[1]
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d.values[1].tolist
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d.values[1].tolist()
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d.values[1].tolist().sum()
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sum(sa_countries_d.values[1].tolist())
def is_sqr(x):
    return math.sqrt(x) % 1 == 0
#Q8: What is the distance between Camp Randall Stadium and the Wisconsin State Capital?
#Haversine Formula (from R.W. Sinnott, "Virtues of the Haversine", Sky and Telescope, vol. 68, no. 2, 1984, p. 159):
def calculate_distance(lat1,lon1,lat2,lon2):
    pi = math.pi
    R = 3956
    dlon = math.radians(lon2) - math.radians(lon1)
    dlat = math.radians(lat2) - math.radians(lat1)
    a = (sin(dlat/2)) ** 2 + cos(lat1) * cos(lat2) * (sin(dlon/2)) ** 2
    a = sqrt(a ** 2)
    c = 2 * asin(min(1,sqrt(a)))
    d = R * c
    return d
(lat1,lon1,lat2,lon2) = [43.070231,-89.411893,43.074645,-89.384113]
dlon = math.radians(lon2) - math.radians(lon1)
dlat = math.radians(lat2) - math.radians(lat1)
dlon
dlat
a = (sin(dlat/2)) ** 2 + cos(lat1) * cos(lat2) * (sin(dlon/2)) ** 2
c = 2 * asin(min(1,sqrt(a)))
a = (sin(dlat/2)) ** 2 + cos(lat1) * cos(lat2) * (sin(dlon/2)) ** 2
a
c = 2 * asin(min(1,sqrt(a)))
c
a = (sin(dlat/2.0)) ** 2.0 + cos(lat1) * cos(lat2) * (sin(dlon/2.0)) ** 2.0
a
c = 2.0 * asin(min(1,sqrt(a)))
c
#Q8: What is the distance between Camp Randall Stadium and the Wisconsin State Capital?
#Haversine Formula (from R.W. Sinnott, "Virtues of the Haversine", Sky and Telescope, vol. 68, no. 2, 1984, p. 159):
def calculate_distance(lat1,lon1,lat2,lon2):
    pi = math.pi
    R = 3956
    dlon = math.radians(lon2) - math.radians(lon1)
    dlat = math.radians(lat2) - math.radians(lat1)
    a = (sin(dlat/2.0)) ** 2.0 + cos(lat1) * cos(lat2) * (sin(dlon/2.0)) ** 2.0
    a = sqrt(a ** 2.0)
    c = 2.0 * asin(min(1,sqrt(a)))
    d = R * c
    return d
calculate_distance(43.070231,-89.411893,43.074645,-89.384113)
def no_nan(x):
    return x not == 'NaN'
def no_nan(x):
    return x == 'NaN'
def no_nan(x):
    return not x == 'NaN'
sa_countries_d.apply(lambda x: x.sum(), axis=1)
filter(no_nan, sa_countries_d[1])
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
filter(no_nan, sa_countries_d[1])
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d.values[1].tolist()
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
filter(no_nan, sa_countries_d.values[1].tolist())
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
list(filter(no_nan, sa_countries_d.values[1].tolist()))
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
list(filter(no_nan, sa_countries_d.values[1].tolist())).mean()
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
sum(list(filter(no_nan, sa_countries_d.values[1].tolist())))
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
sum(list(filter(no_nan, sa_countries_d.values[1].tolist())))/len(select_countries('continent','South America'))
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
def new_sum():
    return sum(list(filter(no_nan, sa_countries_d.values[1].tolist())))/len(select_countries('continent','South America'))
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: x.new_sum(), axis=1)
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: newsum(x), axis=1)
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
def new_sum():
    return sum(list(filter(no_nan, sa_countries_d.values[1].tolist())))/len(select_countries('continent','South America'))
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: new_sum(x), axis=1)
#sa_countries_d.apply(lambda x: x.sum(), axis=1)
def new_sum(x):
    return sum(list(filter(no_nan, x.tolist())))/len(select_countries('continent','South America'))
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: new_sum(x), axis=1)
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: new_sum(x), axis=1)
sa_countries_d
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: new_sum(x), axis=1)
sa_countries_d.loc['Row_sum'] = sa_countries_d.apply(lambda x: new_sum(x))
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_sum'] = sa_countries_d.apply(lambda x: new_sum(x), axis=1)
sa_countries_d.loc['Row_sum'] = sa_countries_d.apply(lambda x: new_sum(x))
sa_countries_d
#Q12: What is the most central country in the South American continent?
sa_countries_d['Col_avg'] = sa_countries_d.apply(lambda x: new_sum(x), axis=1)
sa_countries_d.loc['Row_avg'] = sa_countries_d.apply(lambda x: new_sum(x))
sa_countries_d
#Q11: What is the distance between every pair of countries in the South American continent?
def select_countries(column,keyword):
    return list(countries[(countries[column] == keyword)]['country'])
sa_countries_d = find_group_distance(select_countries('continent','South America'))
sa_countries_d
#Q12: What is the most central country in the South American continent?
new_sa_countries_d = sa_countries_d
new_sa_countries_d['Col_avg'] = new_sa_countries_d.apply(lambda x: new_sum(x), axis=1)
new_sa_countries_d.loc['Row_avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d
#Q12: What is the most central country in the South American continent?
new_sa_countries_d = sa_countries_d
new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d
#Q12: What is the most central country in the South American continent?
new_sa_countries_d = sa_countries_d
new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d
#Q12: What is the most central country in the South American continent?
new_sa_countries_d = sa_countries_d
new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d
#Q12: What is the most central country in the South American continent?
new_sa_countries_d = sa_countries_d
new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d
#Q12: What is the most central country in the South American continent?
new_sa_countries_d = sa_countries_d
new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d
#Q12: What is the most central country in the South American continent?
new_sa_countries_d = sa_countries_d
new_sa_countries_d.loc['Avg'] = new_sa_countries_d.apply(lambda x: new_sum(x))
new_sa_countries_d
#Q12: What is the most central country in the South American continent?

In [400]:
list_1 = [1,2,3,4,5,6, None, 'NaN']
def is_odd(x):
    return x != None

In [401]:
list(filter(is_odd, list_1))

[1, 2, 3, 4, 5, 6, 'NaN']